### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by bb7788** [Moln/php-mysql-replication#12]
> Please provide the following details.

* *Operating System*: Docker Alpine Linux 3.15 
* *PHP Version*: PHP 8.1.1 
* *php-mysql-replication Version*:  1.2.1
* *mysql version (```SELECT VERSION();```): 5.5.68-MariaDB  

> Steps required to reproduce the problem.

貌似有内存泄露，循环随机插入和更新一些内容，内存一直在涨
使用的例子 moln/php-mysql-replication/example/resuming.php
```
$binLogStream = new MySQLReplicationFactory(
    BinLogBootstrap::startFromPosition(new ConfigBuilder())
        ->withUser('admin')
        ->withHost('127.0.0.1')
        ->withPort(3306)
        ->withPassword('admin')
        ->withEventsOnly([
            ConstEventType::UPDATE_ROWS_EVENT_V1, ConstEventType::UPDATE_ROWS_EVENT_V2,
            ConstEventType::WRITE_ROWS_EVENT_V1, ConstEventType::WRITE_ROWS_EVENT_V2,
            ConstEventType::DELETE_ROWS_EVENT_V1, ConstEventType::DELETE_ROWS_EVENT_V2,
        ])
        ->withRetry(2)
        ->withSlaveId(100)
        // ->withHeartbeatPeriod(2)
        ->build(),
    null, null, null, null,
    $logger
);
```
```
    public function allEvents(EventDTO $event): void
    {
        // all events got __toString() implementation
        // echo $event;

        // all events got JsonSerializable implementation
        // echo json_encode($event, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE);

        echo 'Memory usage ' . round(memory_get_usage() / 1048576, 2) . ' MB' . PHP_EOL;

        // save event for resuming it later
        BinLogBootstrap::save($event->getEventInfo()->getBinLogCurrent());
    }
```
```
随机插入的内容
$a = "515919714好多好多好多好多好多电话都好的孩子574865541好多好多好多好多好多电话都好的孩子434685510好多好多好多好多好多电话都好的孩子182305923好多好多好多好多好多电话都好的孩子702967433好多好多好多好多好多电话都好的孩子753493571好多好多好多好多好多电话都好的孩子474263877好多好多好多好多好多电话都好的孩子239080747好多好多好多好多好多电话都好的孩子265003438好多好多好多好多好多电话都好的孩子162751304好多好多好多好多好多电话";
$b = str_split($a,3);
shuffle($b);
$c = implode("",$b);
```

Memory usage 4.77 MB
saving file:mysql-bin.000001, position:553605723 bin log position
Memory usage 4.77 MB
saving file:mysql-bin.000001, position:553606525 bin log position
Memory usage 4.77 MB
saving file:mysql-bin.000001, position:553606704 bin log position
Memory usage 4.77 MB
saving file:mysql-bin.000001, position:553607506 bin log position
Memory usage 4.78 MB
saving file:mysql-bin.000001, position:555711228 bin log position
Memory usage 4.78 MB
saving file:mysql-bin.000001, position:555711407 bin log position
Memory usage 4.78 MB
saving file:mysql-bin.000001, position:555712209 bin log position
Memory usage 4.78 MB
saving file:mysql-bin.000001, position:555712388 bin log position
Memory usage 4.79 MB
saving file:mysql-bin.000001, position:557159570 bin log position
Memory usage 4.79 MB
saving file:mysql-bin.000001, position:557159749 bin log position
Memory usage 4.79 MB
saving file:mysql-bin.000001, position:557160551 bin log position
Memory usage 4.79 MB
saving file:mysql-bin.000001, position:557160730 bin log position

> Expected Result.

* 

> Actual Result.

*

**Comment by Moln** [comment]
我这测试3万条数据，内存在 3.72 MB ~ 4.09 MB 之间。
也有实际的业务应用，运行几个月内存都很稳定。

**Comment by bb7788** [comment]
@Moln 分表的情况您那边是怎么处理的？
